// <auto-generated />
using Machine_Test.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
<<<<<<<< HEAD:Chinnu/Machine_Test/Machine_Test/Migrations/ApplicationDbContextModelSnapshot.cs

#nullable disable

namespace Machine_Test.Migrations
========
using Razor_ServiceRepo.Data;

#nullable disable

namespace Razor_ServiceRepo.Migrations
>>>>>>>> 73448bdaf4ef445f3952b497bfc0a9db31b692de:Razor/Razor_ServiceRepo_Demo/Razor_ServiceRepo/Migrations/ApplicationDbContextModelSnapshot.cs
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<<< HEAD:Chinnu/Machine_Test/Machine_Test/Migrations/ApplicationDbContextModelSnapshot.cs
            modelBuilder.Entity("Machine_Test.Models.User", b =>
========
            modelBuilder.Entity("Razor_ServiceRepo.Models.User", b =>
>>>>>>>> 73448bdaf4ef445f3952b497bfc0a9db31b692de:Razor/Razor_ServiceRepo_Demo/Razor_ServiceRepo/Migrations/ApplicationDbContextModelSnapshot.cs
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
